                                                                                                  pg_get_functiondef                                                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.observation_to_current_occurence()                                                                                                                                                 +
  RETURNS trigger                                                                                                                                                                                                     +
  LANGUAGE plpgsql                                                                                                                                                                                                    +
 AS $function$                                                                                                                                                                                                        +
     DECLARE                                                                                                                                                                                                          +
         v_cop text := TG_OP;                                                                                                                                                                                         +
         v_current_cell_id integer;                                                                                                                                                                                   +
         v_current_obs_id integer;                                                                                                                                                                                    +
         v_status_id integer;                                                                                                                                                                                         +
         v_asset_id integer;                                                                                                                                                                                          +
     BEGIN                                                                                                                                                                                                            +
         -- Identifying the relevant cell ID based on the trigger                                                                                                                                                     +
         IF ((v_cop = 'INSERT') or (v_cop = 'UPDATE')) THEN                                                                                                                                                           +
                 v_current_cell_id := NEW.cell_id;                                                                                                                                                                    +
                 v_current_obs_id  := NEW.observation_id;                                                                                                                                                             +
         ELSE                                                                                                                                                                                                         +
                 v_current_cell_id := OLD.cell_id;                                                                                                                                                                    +
                 v_current_obs_id  := OLD.observation_id;                                                                                                                                                             +
         END IF;                                                                                                                                                                                                      +
         -- Getting the baseline value in case there is no previous observation to roll back to                                                                                                                       +
         SELECT status_id,asset_id into v_status_id,v_asset_id from observation obs,observation_coverage oc where oc.cell_id = v_current_cell_id and obs.id=oc.observation_id order by obs.ts desc limit 1;           +
         -- If not found, because it was the last observation coverage covering this cell                                                                                                                             +
         IF NOT FOUND THEN                                                                                                                                                                                            +
                 SELECT ba.status_id,ba.asset_id into v_status_id,v_asset_id from baseline_occurence ba,observation obs where obs.id = v_current_obs_id and ba.asset_id=obs.asset_id and ba.cell_id=v_current_cell_id;+
                 -- Should we be deleting the observation this coverage was a representant of?                                                                                                                        +
                 -- Couldn't find a way to do that without breaking the cleanup                                                                                                                                       +
         END IF;                                                                                                                                                                                                      +
                                                                                                                                                                                                                      +
         -- We should be executing a function that is always able to give the correct current occurence based on baseline and observations                                                                            +
         update current_occurence set status_id = v_status_id where cell_id=v_current_cell_id and asset_id = v_asset_id;                                                                                              +
                                                                                                                                                                                                                      +
         RETURN NULL; -- result is ignored since this is an AFTER trigger                                                                                                                                             +
     END;                                                                                                                                                                                                             +
 $function$                                                                                                                                                                                                           +
 
(1 row)

